# Generated by Django 5.2.8 on 2025-11-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "id",
                        "created_at",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("status", models.CharField(max_length=20, verbose_name="Статус")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "db_table": "django_orders",
            },
        ),
    ]
