# Generated by Django 5.2.8 on 2025-11-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partitions", "0002_alter_order_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
